name: Deploy Backend to Deploy Branch

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - "package.json"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure package.json is in server directory
        run: |
          cp package.json server/

      - name: Deploy to Deploy Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: ./server
          keep_files: true
